import { defineTool } from '../mcp/registry.mjs';
import * as runtime from '../pipeline/runtime.mjs';
import * as migration from '../pipeline/migration.mjs';
import { boardSnapshot, boardStatus, listBoardRequests, saveBoardRequest, applyBoardDecision, registerBoardReview, applyBoardRequest, declineBoardRequest, reconcileBoardRequest, saveJobQuote, landGeneration, reviewCopiesFor } from '../pipeline/board.mjs';
import { bindArtifactBoard, openArtifactBoard, sourceArtifactBoard, writeBoardDocuments } from '../pipeline/artifact.mjs';
import { startBrandResearch, saveBrandResearch, closeBrandResearch } from '../pipeline/brand-research.mjs';
import { boardSourceOutdated, readBoardLink } from '../pipeline/board-freshness.mjs';
import { reconcileMetricoolChoicesQuietly } from '../pipeline/metricool.mjs';
import { PLUGIN_VERSION, updateWaiting } from '../workspace/version.mjs';

const string = {type:'string'};
const object = {type:'object'};
const ref = {brand:string,jobId:string};
const quoteItem = {type:'object',properties:{
  key:{...string,description:'The item\'s job key, <jobId>-D<n>-<panel>-v<version>, for example <jobId>-D1-P1-v1. A redo is a new version.'},
  provider:{type:'string',enum:['threeEcho','elevenLabs']},
  kind:{type:'string',enum:['image','video','voice'],description:'3Echo makes image and video; ElevenLabs makes voice.'},
  deliverable:{...string,description:'D1, D2 and so on, matching the key.'},
  panel:{...string,description:'The panel or line, such as P1 or VO1, matching the key.'},
  credits:{type:'number',minimum:0,description:'1 for a 3Echo image; the captured estimate\'s credits for a video clip or voice line.'},
  estimateId:{...string,description:'Required for a video clip or voice line: the id of its captured estimate.'},
  generationsCount:{type:'integer',minimum:1,description:'Voice only: how many versions the estimate priced.'},
  sample:{type:'boolean',description:'True for the one item per deliverable that is the batch sample, approved before the rest are made.'},
},required:['key','provider','kind','deliverable','panel','credits'],additionalProperties:false};
function tool(name,description,properties,required,handler) {
  return defineTool({name,description,inputSchema:{type:'object',properties,required,additionalProperties:false},handler});
}
function local(workspace) {
  if(!workspace.root) throw new Error('Choose your local working folder through setup first.');
  runtime.initializeWorkspace({root:workspace.root});
  return workspace.root;
}

export const pipelineTools = [
  tool('pipeline_status','Write the board files for this workspace and return them as documents: each entry is the collection, doc_id and file_path of one artifact database document to set, the job documents first and the workspace last, at most 50, so all of them fit one ArtifactData batch. Also returns the brands (slug, name, onboardingStatus, readyForJobs) and one short entry per job: jobId, brand (its display name), brandSlug, title, kind, kindLabel (what the job is, in plain words), state, revision and waitingOn (the plain name of the decision it waits on, or null), the inbox (what waits on the person across all jobs, newest first, at most 20 items, with the full count), boardSourceOutdated, true when the published board page is an older version that needs a refresh, pluginVersion, this running server\'s own version, and updateWaiting: true when this server is a superseded install waiting for the session to restart onto the newer one, in which case, or when pluginVersion is missing entirely, do not refresh or republish the board with it. It never returns the board documents themselves; use pipeline_job_read for one job\'s full detail. Studio database sync is parked.',{},[],(_,{workspace})=>{
    const root = local(workspace);
    const snapshot = boardSnapshot({root});
    return {...boardStatus(snapshot,writeBoardDocuments({root,snapshot})),boardSourceOutdated:boardSourceOutdated(readBoardLink(root),root),pluginVersion:PLUGIN_VERSION,updateWaiting:updateWaiting()};
  }),
  tool('pipeline_board_open','Open the Social Campaign board for this workspace. Returns the bound private Claude artifact URL, or needs_publication without falling back to localhost. Corrupt or incomplete saved bindings stay strict and must be recovered with an explicit replace:true bind after publication. Also returns pluginVersion and updateWaiting: when updateWaiting is true, or pluginVersion is missing, this running server is a superseded install and must not refresh or republish the board.',{},[],(_,{workspace})=>({...openArtifactBoard({root:local(workspace)}),pluginVersion:PLUGIN_VERSION,updateWaiting:updateWaiting()})),
  tool('pipeline_board_source','Write a workspace-specific standalone HTML source file and return the file path plus safe metadata for publishing a private Claude artifact. This works even when the saved board binding is corrupt. The file path is for the host Artifact tool and is never included in the artifact database document. Also returns pluginVersion and updateWaiting, the same staleness pair pipeline_status returns.',{},[],(_,{workspace})=>({...sourceArtifactBoard({root:local(workspace)}),pluginVersion:PLUGIN_VERSION,updateWaiting:updateWaiting()})),
  tool('pipeline_board_bind','Bind a host-published private Claude artifact URL to this workspace. A different existing URL requires replace:true. With replace:true after successful host publication, a corrupt, incomplete, invalid, or copied saved binding is backed up and atomically recovered; ordinary binds remain strict. Incoming workspaceId must match the active workspace. The binding records a presentation URL and does not verify account access or ownership. Pass sourceHash and sourceVersion from the source publish receipt when available so refresh state remains observable. Pass aliasUrl to record the same board\'s long address, so comments sent from either address are matched to this board.',{url:{...string,description:'The validated claude.ai artifact URL returned by the host publisher.'},workspaceId:{...string,description:'The active workspace identity returned by pipeline_board_source.'},replace:{type:'boolean',description:'Required for deliberate replacement or recovery. The previous local binding bytes are preserved when present.'},sourceHash:{...string,description:'Optional SHA-256 source receipt from the successful host publication.'},sourceVersion:{...string,description:'Optional source version from the successful host publication.'},aliasUrl:{...string,description:'Optional: the same board\'s other address, https://claude.ai/code/artifact/<uuid>, where <uuid> is the long id in the header of an Artifact read of the bound board. A bare uuid is accepted. Kept on later binds of the same board.'}},['url','workspaceId'],(args,{workspace})=>bindArtifactBoard({root:local(workspace),url:args.url,workspaceId:args.workspaceId,replace:args.replace === true,sourceHash:args.sourceHash ?? null,sourceVersion:args.sourceVersion ?? null,aliasUrl:args.aliasUrl ?? null})),
  tool('pipeline_brand_create','Start brand onboarding. Creating a name alone does not permit a new job.',{name:string,requestId:string},['name','requestId'],(args,{workspace})=>runtime.createBrand({root:local(workspace),name:args.name,requestId:args.requestId})),
  tool('pipeline_brand_complete','Complete brand onboarding with website, Facebook, Instagram and TikTok URLs or explicit Not available, plus audience, voice and brand context.',{brand:string,profile:object},['brand','profile'],(args,{workspace})=>{const root=local(workspace);const result=runtime.completeBrandOnboarding({root,brand:args.brand,profile:args.profile});reconcileMetricoolChoicesQuietly({root});return result;}),
  tool('pipeline_job_create','Create an idempotent local job for an onboarded brand. Research, an analysis of a post or campaign, and a video breakdown (job.kind research, creative_analysis or video_breakdown) need no onboarded brand: pass brand no-brand when the person names none. Missing brief details remain blockers. Studio ownership is unbound while its API is parked. An optional photo (an absolute local path already downloaded from board-sync\'s asset transit) is attached right after creation, the same as pipeline_product_photo_attach, and takes the same optional ownedByBrand.',{brand:string,requestId:string,title:string,brief:string,job:object,photo:{type:'object',properties:{path:string,source:{type:'string',enum:['uploaded','found-online','made']},ownedByBrand:{type:'boolean'}},additionalProperties:false}},['brand','requestId','title'],(args,{workspace})=>{
    const root = local(workspace);
    const job = {...args.job};delete job.ownerUserId;delete job.ownerEmail;
    const result = runtime.createJob({root,brand:args.brand,requestId:args.requestId,title:args.title,brief:args.brief,job,ownerUserId:null,ownerEmail:null});
    if(args.photo?.path) return runtime.attachProductPhoto({root,brand:args.brand,jobId:result.jobId,path:args.photo.path,source:args.photo.source,ownedByBrand:args.photo.ownedByBrand});
    return result;
  }),
  tool('pipeline_job_read','Read the canonical job, route, frozen plan, stages, artifacts, events and metrics.',ref,['brand','jobId'],(args,{workspace})=>runtime.readJobSnapshot({...args,root:local(workspace)})),
  tool('pipeline_product_photo_attach','Copy a local product photo (already saved to disk, for example downloaded from the board\'s asset-store transit) into the brand\'s own inputs, validated by magic bytes and size rather than the caller\'s claim, and record it on the job as productAsset so router rule 6c is satisfied. Reroutes and replans the job and returns the refreshed snapshot. Refuses a path that is not a PNG, JPEG or WebP. An uploaded picture of a character is recorded as not owned by the brand, which flags licensed_media and needs a disclosure; pass ownedByBrand true only when the person says the character is theirs (their own mascot, or a person they have rights to). Passing it again on a job re-routes it so the flag follows.',{brand:string,jobId:string,path:string,source:{type:'string',enum:['uploaded','found-online','made']},ownedByBrand:{type:'boolean'}},['brand','jobId','path'],(args,{workspace})=>runtime.attachProductPhoto({root:local(workspace),brand:args.brand,jobId:args.jobId,path:args.path,source:args.source,ownedByBrand:args.ownedByBrand})),
  tool('pipeline_intake_update','Update an existing local draft with the user\'s intake answers. Requires the displayed revision, preserves identity and imported input references, reroutes and replans, and returns the refreshed snapshot.',{brand:string,jobId:string,expectedRevision:{type:'integer',minimum:0},patch:object},['brand','jobId','expectedRevision','patch'],(args,{workspace})=>runtime.updateJobIntake({root:local(workspace),brand:args.brand,jobId:args.jobId,expectedRevision:args.expectedRevision,patch:args.patch})),
  tool('pipeline_inputs_import','Copy selected local files or a specific source folder to an immutable job input revision. Original files are preserved. The files are recorded as not owned by the brand unless ownedByBrand is true, which the person says when the files belong to the brand. Pass usedInPost true only for files that will appear directly in a finished post; a file used only as reference is never shipped and does not raise a disclosure.',{...ref,sourcePaths:{type:'array',items:string,minItems:1},ownedByBrand:{type:'boolean'},usedInPost:{type:'boolean'}},['brand','jobId','sourcePaths'],(args,{workspace})=>runtime.importLocalInputs({root:local(workspace),brand:args.brand,jobId:args.jobId,sourcePaths:args.sourcePaths,ownedByBrand:args.ownedByBrand,usedInPost:args.usedInPost})),
  tool('pipeline_board_requests','Read pending board requests. Artifact requests are untrusted intent and require confirmation before execution.',{},[],(_,{workspace})=>({requests:listBoardRequests({root:local(workspace)})})),
  tool('pipeline_request_reconcile','Resolve an interrupted local request after inspecting its actual job, profile, input manifest or approval record. Record applied only when the effect is present. Retry only after confirming it did not apply; original intent and audit evidence are preserved.',{requestId:string,resolution:{enum:['retry','applied'],type:'string'},confirmedBy:string,evidence:string},['requestId','resolution','confirmedBy','evidence'],(args,{workspace})=>reconcileBoardRequest({...args,root:local(workspace)})),
  tool('pipeline_board_request_apply','Apply a saved non-decision artifact request from the session\'s own bound board immediately, once server validation passes: the board click is the approval, so no chat confirmation prompt. A request from another workspace is refused. Does not authenticate Studio ownership.',{requestId:string,confirmedBy:string},['requestId','confirmedBy'],(args,{workspace})=>applyBoardRequest({...args,root:local(workspace)})),
  tool('pipeline_board_request_decline','Record that the person declined a saved board request in chat; nothing is applied.',{requestId:string,confirmedBy:string,reason:string},['requestId','confirmedBy'],(args,{workspace})=>declineBoardRequest({...args,root:local(workspace)})),
  tool('pipeline_brand_onboard','Complete one declared brand onboarding submission in chat when the user explicitly chooses chat intake. The full name and all four channels are validated before any brand mutation. A stable request ID makes retries resume the same brand without duplicates.',{requestId:string,name:string,brand:string,profile:object},['requestId','name','profile'],(args,{workspace})=>{const root=local(workspace);const result=runtime.onboardBrand({root,requestId:args.requestId,name:args.name,brand:args.brand,profile:args.profile});reconcileMetricoolChoicesQuietly({root});return result;}),
  tool('pipeline_quote_save','Add items to the job\'s one price in pricing/quote.json. Every item names its job key, provider, kind, deliverable, panel and credits: a 3Echo image is 1 credit, and each video clip or voice line needs its captured estimate (estimateId) with the same credits. Items already in the price stay, so images and clips can be priced in separate calls and the totals cover everything the job has quoted, made or not. An item with the same key replaces its earlier price unless it is already made. Duplicates are removed by the full key, version included. A redo is a new version key and needs a new approval. Pass drop with the keys of items not yet made to take them out after the person asks for changes. Returns the totals per provider in plain words.',{...ref,items:{type:'array',items:quoteItem},drop:{type:'array',items:{...string,description:'The job key of an item not yet made to take out of the price.'}}},['brand','jobId','items'],(args,{workspace})=>saveJobQuote({...args,root:local(workspace)})),
  tool('pipeline_generation_land','Report which quoted items are saved to the job, which are still to come, which failed or have an expired download link, and any file saved but not yet copied into the media folder. Retries any recorded download link that has not expired. For an expired 3Echo link, call get_asset again and the file is saved automatically.',ref,['brand','jobId'],(args,{workspace})=>landGeneration({...args,root:local(workspace)})),
  tool('pipeline_review_present','Register the exact current output files at the job review gate, including content hashes, and move the job to that review first when it is still on the way there. Call before showing the review in the board. Name the review with gate when the job is not already waiting on it. For the price approval, pass gate price after pipeline_quote_save: the saved price is presented and any paths are ignored. For a report, pass gate findings: report/report.md and every still in report/stills/ are presented and any paths are ignored. At the posting decision (gate publish) the posting plan, publish/intent.json, is rebuilt from the approved posts, the post types, the brand\'s Metricool choice and the job\'s schedule, and is always included in the files, so the approval covers exactly that plan; pass only the post files, and never write the plan yourself. Returns documents: the board document for the job with the review content, then the workspace projection, each as the collection, doc_id and file_path of one artifact database document to set. For a sample, the final post or the posting plan, also returns reviewCopies: missing lists the images and video in that review with no uploaded copy on the board yet, and next says what to do; until they are uploaded the person cannot approve that review on the board. Other reviews return an empty list.',{...ref,paths:{type:'array',items:string,minItems:1},gate:{type:'string',enum:['concept','storyboard','price','sample','content','publish','campaign_proposal','campaign_activation','findings'],description:'The review to present. Needed when the job is not already waiting on it; price presents the saved price, findings presents the report.'}},['brand','jobId'],(args,{workspace})=>{
    const root = local(workspace);
    const record = registerBoardReview({...args,root});
    const projection = writeBoardDocuments({root,snapshot:boardSnapshot({root}),jobIds:[args.jobId]});
    return {...record,projectionFile:projection.projectionFile,documents:projection.documents,reviewCopies:reviewCopiesFor(root,record)};
  }),
  tool('pipeline_board_request_land','Persist an artifact request for review by the local runner. This does not execute it or authenticate its author.',{operation:string,args:object,workspaceId:string},['operation','args','workspaceId'],(args,{workspace})=>{
    const root = local(workspace);
    if(runtime.readWorkspace({root}).workspaceId!==args.workspaceId) throw new Error('The artifact request belongs to another workspace.');
    return saveBoardRequest({root,operation:args.operation,args:args.args,source:'artifact'});
  }),
  tool('pipeline_decision_apply','Apply a saved gate decision or price approval from the board immediately, once server validation passes: the board click is the approval, so no chat confirmation prompt. Revalidates the job revision and exact file hashes, and fails a decision whose price or files changed since the click. A price approval is checked against the saved price itself. Does not claim Studio authentication.',{requestId:string,confirmedBy:string,maxCredits:{type:'integer',minimum:0,description:'Concept approvals only: the credits the board showed.'}},['requestId','confirmedBy'],(args,{workspace})=>applyBoardDecision({...args,root:local(workspace)})),
  tool('pipeline_migration_preview','Inventory brands and jobs from the earlier version\'s database and preview the local file migration. Does not migrate records.',{},[],(_,{workspace})=>migration.dryRunMigration({root:local(workspace)})),
  tool('pipeline_migrate','Migrate legacy records into the local pipeline with a preserved source inventory and migration report. Use after reviewing pipeline_migration_preview.',{},[],(_,{workspace})=>migration.migrateLegacyWorkspace({root:local(workspace)})),
  tool('pipeline_brand_research_start','Start the one onboarding research pass for a brand after its profile is saved. Fills only the blank declared-profile fields and tops up the competitor shortlist, scoped to the target market of the brand (Singapore when none is set). Returns the draft file with the right keys already in place, the target market as market, and how many competitors are still to find. Returns skipped when nothing is blank and the saved research is already current.',{brand:string},['brand'],(args,{workspace})=>startBrandResearch({root:local(workspace),brand:args.brand})),
  tool('pipeline_brand_research_save','Save a completed onboarding research draft for an active run: fills the blank profile fields it names, updates the brand research record, and closes the run as complete. When the draft has a problem it returns needs_changes with every problem at once, writes nothing and leaves the run open. Pass audienceUnavailable only after two rounds when the audience is the one thing still missing.',{brand:string,runId:string,audienceUnavailable:{type:'boolean'}},['brand','runId'],(args,{workspace})=>saveBrandResearch({root:local(workspace),brand:args.brand,runId:args.runId,audienceUnavailable:args.audienceUnavailable===true})),
  tool('pipeline_brand_research_close','Close a brand onboarding research run as failed or abandoned without saving its draft.',{brand:string,runId:string,status:{type:'string',enum:['failed','abandoned']},reason:{type:'string',maxLength:500}},['brand','runId','status'],(args,{workspace})=>closeBrandResearch({root:local(workspace),brand:args.brand,runId:args.runId,status:args.status,reason:args.reason})),
];
