-- 001_init.sql
-- The Social Campaign creative database.
--
-- Conventions used by every table here:
--   * ids are TEXT, generated by server/lib/ids.mjs, sortable by creation time
--   * timestamps are TEXT, ISO 8601, UTC
--   * a column named json or ending in _json holds JSON text
--   * enumerated values are enforced with CHECK constraints, never in application code alone

-- Workspace level key/value facts: schema owner, workspace id, created_at, plugin version.
CREATE TABLE workspace_meta (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Brand memory
-- ---------------------------------------------------------------------------

CREATE TABLE brands (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL UNIQUE,
  website     TEXT,
  status      TEXT NOT NULL DEFAULT 'active'
              CHECK (status IN ('active', 'archived')),
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

-- One row per brand fact, so provenance and confidence live at field level rather
-- than being smeared across a single brand document.
CREATE TABLE brand_fields (
  id                TEXT PRIMARY KEY,
  brand_id          TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  field_path        TEXT NOT NULL,               -- for example identity.tagline
  value_json        TEXT NOT NULL,
  source_type       TEXT NOT NULL
                    CHECK (source_type IN (
                      'user_correction',
                      'user_brand_guide',
                      'official_source',
                      'verified_research',
                      'model_inference'
                    )),
  source_ref        TEXT,                        -- url, file path or tool reference
  observed_at       TEXT NOT NULL,
  last_verified_at  TEXT,
  confidence        REAL NOT NULL DEFAULT 0.5
                    CHECK (confidence >= 0 AND confidence <= 1),
  precedence_rank   INTEGER NOT NULL DEFAULT 50, -- lower wins, see docs/CONTRACTS.md
  superseded_by     TEXT REFERENCES brand_fields(id) ON DELETE SET NULL,
  created_at        TEXT NOT NULL
);

CREATE INDEX idx_brand_fields_brand ON brand_fields (brand_id, field_path);
CREATE INDEX idx_brand_fields_live ON brand_fields (brand_id, field_path, precedence_rank)
  WHERE superseded_by IS NULL;

-- The synthesized creative intelligence for a brand: formats, hooks, structures,
-- talent patterns, shot grammar, pacing, product treatment, CTA style.
CREATE TABLE creative_profiles (
  id          TEXT PRIMARY KEY,
  brand_id    TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  version     INTEGER NOT NULL DEFAULT 1,
  json        TEXT NOT NULL,
  summary     TEXT,
  created_at  TEXT NOT NULL,
  UNIQUE (brand_id, version)
);

-- ---------------------------------------------------------------------------
-- Creative library
-- ---------------------------------------------------------------------------

-- Assets are referenced in place by default. path points at the original file and is
-- never modified, renamed, moved or deleted by this plugin.
CREATE TABLE assets (
  id             TEXT PRIMARY KEY,
  brand_id       TEXT REFERENCES brands(id) ON DELETE SET NULL,
  path           TEXT NOT NULL,
  sha256         TEXT,
  mime           TEXT,
  kind           TEXT NOT NULL DEFAULT 'other'
                 CHECK (kind IN ('video', 'image', 'audio', 'document', 'script', 'other')),
  bytes          INTEGER,
  width          INTEGER,
  height         INTEGER,
  duration       REAL,
  fps            REAL,
  codec          TEXT,
  audio_tracks   INTEGER,
  thumbnail_path TEXT,
  indexed_at     TEXT,
  origin         TEXT NOT NULL DEFAULT 'reference'
                 CHECK (origin IN ('reference', 'generated', 'imported')),
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

CREATE UNIQUE INDEX idx_assets_path ON assets (path);
CREATE INDEX idx_assets_sha ON assets (sha256);
CREATE INDEX idx_assets_brand_kind ON assets (brand_id, kind);

-- One row per analyst pass over an asset. Keeping analyses separate from assets means
-- a re-analysis never destroys the previous reading.
CREATE TABLE asset_analyses (
  id          TEXT PRIMARY KEY,
  asset_id    TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  analyst     TEXT NOT NULL,   -- video-analyst, image-analyst, script-analyst, media-librarian
  json        TEXT NOT NULL,
  created_at  TEXT NOT NULL
);

CREATE INDEX idx_asset_analyses_asset ON asset_analyses (asset_id, analyst);

-- ---------------------------------------------------------------------------
-- Competitor intelligence
-- ---------------------------------------------------------------------------

CREATE TABLE competitors (
  id          TEXT PRIMARY KEY,
  brand_id    TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  website     TEXT,
  handles_json TEXT NOT NULL DEFAULT '{}',
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

CREATE INDEX idx_competitors_brand ON competitors (brand_id);

CREATE TABLE competitor_analyses (
  id            TEXT PRIMARY KEY,
  competitor_id TEXT NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  analyst       TEXT NOT NULL,
  scope         TEXT NOT NULL DEFAULT 'organic'
                CHECK (scope IN ('organic', 'paid', 'mixed')),
  json          TEXT NOT NULL,
  created_at    TEXT NOT NULL
);

CREATE INDEX idx_competitor_analyses_competitor ON competitor_analyses (competitor_id);

-- ---------------------------------------------------------------------------
-- User preference memory, kept apart from brand memory on purpose
-- ---------------------------------------------------------------------------

-- Raw signals. A single inferred choice is campaign evidence only.
CREATE TABLE preference_evidence (
  id          TEXT PRIMARY KEY,
  kind        TEXT NOT NULL CHECK (kind IN ('explicit', 'inferred', 'one_off')),
  signal      TEXT NOT NULL,   -- for example copy.tone, media.aspect_ratio
  value       TEXT NOT NULL,
  campaign_id TEXT REFERENCES campaigns(id) ON DELETE SET NULL,
  confidence  REAL NOT NULL DEFAULT 0.3
              CHECK (confidence >= 0 AND confidence <= 1),
  created_at  TEXT NOT NULL
);

CREATE INDEX idx_preference_evidence_signal ON preference_evidence (signal, kind);

-- Promoted preferences. Explicit signals land here immediately, inferred signals only
-- after repeated consistent evidence.
CREATE TABLE preferences (
  id             TEXT PRIMARY KEY,
  signal         TEXT NOT NULL UNIQUE,
  value          TEXT NOT NULL,
  source_kind    TEXT NOT NULL CHECK (source_kind IN ('explicit', 'inferred')),
  confidence     REAL NOT NULL DEFAULT 0.6
                 CHECK (confidence >= 0 AND confidence <= 1),
  evidence_count INTEGER NOT NULL DEFAULT 1,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Campaigns and job state
-- ---------------------------------------------------------------------------

CREATE TABLE campaigns (
  id             TEXT PRIMARY KEY,
  brand_id       TEXT REFERENCES brands(id) ON DELETE SET NULL,
  title          TEXT,
  job_type       TEXT NOT NULL
                 CHECK (job_type IN ('social_post', 'ad_campaign', 'ugc', 'analyze_existing')),
  starting_point TEXT NOT NULL DEFAULT 'scratch'
                 CHECK (starting_point IN ('scratch', 'reference', 'existing_creative')),
  platforms      TEXT NOT NULL DEFAULT '[]',   -- JSON array of facebook|instagram|tiktok
  status         TEXT NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active', 'waiting', 'completed', 'abandoned')),
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

CREATE INDEX idx_campaigns_brand ON campaigns (brand_id, status);

CREATE TABLE job_plans (
  id          TEXT PRIMARY KEY,
  campaign_id TEXT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  json        TEXT NOT NULL,
  version     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL,
  UNIQUE (campaign_id, version)
);

CREATE TABLE job_stages (
  id           TEXT PRIMARY KEY,
  campaign_id  TEXT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  stage        TEXT NOT NULL,
  status       TEXT NOT NULL
               CHECK (status IN ('required', 'completed', 'skipped', 'not_applicable', 'waiting')),
  stage_order  INTEGER NOT NULL DEFAULT 0,
  detail       TEXT,
  updated_at   TEXT NOT NULL,
  UNIQUE (campaign_id, stage)
);

CREATE INDEX idx_job_stages_order ON job_stages (campaign_id, stage_order);

-- Anything a stage produced: research results, strategy sets, copy, media plans,
-- publishing packages. Either path or json is set; kind says how to read it.
CREATE TABLE artifacts (
  id          TEXT PRIMARY KEY,
  campaign_id TEXT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  kind        TEXT NOT NULL,
  path        TEXT,
  json        TEXT,
  version     INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL,
  UNIQUE (campaign_id, kind, version)
);

CREATE INDEX idx_artifacts_campaign ON artifacts (campaign_id, kind);

-- ---------------------------------------------------------------------------
-- Human approval gates
-- ---------------------------------------------------------------------------

CREATE TABLE reviews (
  id            TEXT PRIMARY KEY,
  campaign_id   TEXT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  kind          TEXT NOT NULL CHECK (kind IN ('strategy', 'cost', 'media', 'final')),
  payload       TEXT NOT NULL,             -- what the user was shown
  decision      TEXT,                      -- what the user chose
  status        TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'resolved')),
  created_at    TEXT NOT NULL,
  resolved_at   TEXT
);

CREATE INDEX idx_reviews_campaign ON reviews (campaign_id, kind, status);

-- ---------------------------------------------------------------------------
-- Event log, spec section 34. V2 analytics reads this table.
-- ---------------------------------------------------------------------------

CREATE TABLE events (
  id          TEXT PRIMARY KEY,
  campaign_id TEXT REFERENCES campaigns(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  payload     TEXT NOT NULL DEFAULT '{}',
  created_at  TEXT NOT NULL
);

CREATE INDEX idx_events_campaign ON events (campaign_id, created_at);
CREATE INDEX idx_events_name ON events (name, created_at);

-- ---------------------------------------------------------------------------
-- Memory proposals. Specialists propose, the memory service promotes.
-- ---------------------------------------------------------------------------

CREATE TABLE memory_proposals (
  id          TEXT PRIMARY KEY,
  target      TEXT NOT NULL CHECK (target IN ('brand', 'creative', 'competitor')),
  brand_id    TEXT REFERENCES brands(id) ON DELETE CASCADE,
  json        TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'proposed'
              CHECK (status IN ('proposed', 'promoted', 'rejected')),
  proposed_by TEXT NOT NULL,
  reason      TEXT,
  created_at  TEXT NOT NULL,
  resolved_at TEXT
);

CREATE INDEX idx_memory_proposals_status ON memory_proposals (status, target);
