#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export function buildBoard({ config = {}, rootDir = root } = {}) {
  const src = join(rootDir, 'board', 'src');
  const html = readFileSync(join(src, 'social-campaign.html'), 'utf8');
  const css = readFileSync(join(src, 'board.css'), 'utf8');
  const js = readFileSync(join(src, 'board.js'), 'utf8');
  const logo = `data:image/png;base64,${readFileSync(join(src, 'logo-reversed.png')).toString('base64')}`;
  const safeConfig = JSON.stringify(config).replace(/</g, '\\u003c');
  return '<!-- Generated by scripts/build-board.mjs. Edit board/src instead. -->\n' + html
    .replace('<!--BOARD_CSS-->', () => `<style>\n${css}\n</style>`)
    .replace('<script id="board-logo" type="text/plain">__BOARD_LOGO_DATA_URI__</script>', () => `<script id="board-logo" type="text/plain">${logo}</script>`)
    .replace('<script id="board-config" type="application/json">{}</script>', () => `<script id="board-config" type="application/json">${safeConfig}</script>`)
    .replace('<!--BOARD_JS-->', () => `<script type="module">\n${js.replace(/<\/script/gi, '<\\/script')}\n</script>`);
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const output = join(root, 'board', 'social-campaign.html');
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, buildBoard());
  process.stdout.write(`Built ${output}\n`);
}
