#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { minifyCss, minifyJs } from './minify-board.mjs';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
// The job-type words the board shows (pipeline names, card labels, report kinds) come from the pipeline
// catalogue of the tree being built, so a new kind needs no board constant. A catalogue that does not line
// up with the registries throws here, so a broken board is never built.
function catalogueConfig(rootDir) {
  return createRequire(import.meta.url)(join(rootDir, 'pipeline', 'scripts', 'lib-catalogue.js')).boardConfig();
}
export function buildBoard({ config = {}, rootDir = root } = {}) {
  const src = join(rootDir, 'board', 'src');
  const html = readFileSync(join(src, 'social-campaign.html'), 'utf8');
  const css = minifyCss(readFileSync(join(src, 'board.css'), 'utf8'));
  const js = minifyJs(readFileSync(join(src, 'board.js'), 'utf8'));
  const logo = `data:image/webp;base64,${readFileSync(join(src, 'logo-reversed.webp')).toString('base64')}`;
  const safeConfig = JSON.stringify({ ...catalogueConfig(rootDir), ...config }).replace(/</g, '\\u003c');
  return '<!-- Generated by scripts/build-board.mjs. Edit board/src instead. -->\n' + html
    .replace('<!--BOARD_CSS-->', () => `<style>\n${css}\n</style>`)
    .replace('<script id="board-logo" type="text/plain">__BOARD_LOGO_DATA_URI__</script>', () => `<script id="board-logo" type="text/plain">${logo}</script>`)
    .replace('<script id="board-config" type="application/json">{}</script>', () => `<script id="board-config" type="application/json">${safeConfig}</script>`)
    .replace('<!--BOARD_JS-->', () => `<script type="module">\n${js.replace(/<\/script/gi, '<\\/script')}\n</script>`);
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const output = join(root, 'board', 'social-campaign.html');
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, buildBoard());
  process.stdout.write(`Built ${output}\n`);
}
