#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { minifyCss, minifyJs } from './minify-board.mjs';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
// The job-type words the board shows (pipeline names, card labels, report kinds) come from the pipeline
// catalogue of the tree being built, so a new kind needs no board constant. A catalogue that does not line
// up with the registries throws here, so a broken board is never built.
function catalogueConfig(rootDir) {
  return createRequire(import.meta.url)(join(rootDir, 'pipeline', 'scripts', 'lib-catalogue.js')).boardConfig();
}
export function buildBoard({ config = {}, rootDir = root } = {}) {
  const src = join(rootDir, 'board', 'src');
  const html = readFileSync(join(src, 'social-campaign.html'), 'utf8');
  const css = minifyCss(readFileSync(join(src, 'board.css'), 'utf8'));
  const js = minifyJs(readFileSync(join(src, 'board.js'), 'utf8'));
  const logo = `data:image/webp;base64,${readFileSync(join(src, 'logo-reversed.webp')).toString('base64')}`;
  const safeConfig = JSON.stringify({ ...catalogueConfig(rootDir), ...config }).replace(/</g, '\\u003c');
  return '<!-- Generated by scripts/build-board.mjs. Edit board/src instead. -->\n' + html
    .replace('<!--BOARD_CSS-->', () => `<style>\n${css}\n</style>`)
    .replace('<script id="board-logo" type="text/plain">__BOARD_LOGO_DATA_URI__</script>', () => `<script id="board-logo" type="text/plain">${logo}</script>`)
    .replace('<script id="board-config" type="application/json">{}</script>', () => `<script id="board-config" type="application/json">${safeConfig}</script>`)
    .replace('<!--BOARD_JS-->', () => `<script type="module">\n${js.replace(/<\/script/gi, '<\\/script')}\n</script>`);
}
// The published form: a tiny page shell plus board.js and board.css as supporting files. The host's Artifact tool
// makes an agent read every line of a large page before it may republish it, so the page stays small (the document
// skeleton, the per-workspace config and two references) and the weight lives in files the tool does not make it read.
// The logo is static, so it rides at the head of board.js (which is then the same for every workspace) instead of
// inflating the shell. The ?v= hash of the two files changes the shell on every release and busts any cache.
export const BOARD_SHELL_FILES = Object.freeze({ js: 'board.js', css: 'board.css' });
export function buildBoardShell({ config = {}, rootDir = root } = {}) {
  const src = join(rootDir, 'board', 'src');
  const html = readFileSync(join(src, 'social-campaign.html'), 'utf8');
  const css = minifyCss(readFileSync(join(src, 'board.css'), 'utf8'));
  const logo = `data:image/webp;base64,${readFileSync(join(src, 'logo-reversed.webp')).toString('base64')}`;
  const js = `globalThis.__boardLogo=${JSON.stringify(logo)};\n${minifyJs(readFileSync(join(src, 'board.js'), 'utf8'))}`;
  const version = createHash('sha256').update(js, 'utf8').update('\0').update(css, 'utf8').digest('hex').slice(0, 12);
  const safeConfig = JSON.stringify({ ...catalogueConfig(rootDir), ...config }).replace(/</g, '\\u003c');
  const page = '<!-- Generated by scripts/build-board.mjs. Edit board/src instead. -->\n' + html
    .replace('<!--BOARD_CSS-->', () => `<link rel="stylesheet" href="${BOARD_SHELL_FILES.css}?v=${version}">`)
    .replace('  <script id="board-logo" type="text/plain">__BOARD_LOGO_DATA_URI__</script>\n', () => '')
    .replace('<script id="board-config" type="application/json">{}</script>', () => `<script id="board-config" type="application/json">${safeConfig}</script>`)
    .replace('<!--BOARD_JS-->', () => `<script type="module" src="${BOARD_SHELL_FILES.js}?v=${version}"></script>`);
  return { html: page, js, css, version };
}
// What a source hash covers: the shell and both files, so a change to either file counts as a changed board.
export function boardShellHashInput(parts) {
  return `${parts.html}\0${parts.js}\0${parts.css}`;
}
export function buildBoardShellText(options) {
  return boardShellHashInput(buildBoardShell(options));
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const output = join(root, 'board', 'social-campaign.html');
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, buildBoard());
  process.stdout.write(`Built ${output}\n`);
}
